### ISSUE TITLE
Static Content Spec

### ISSUE THREAD

**Issue by super3** [super3/invictus.io#1]
**From core spec:**
Static Content or Basic PHP to manage headers/footers/language translation is preferred to systems dependent upon databases.  The site should load quickly and the content should be easily updated and versioned with github.  To test/deploy the site should be as simple as a git pull into the document root of a PHP enabled server.

**Todo:**
- [x] Deploy Invictus Website on Webserver 
- [x] Use Cron Job to Automatically Update Webserver every 10 minutes from Repo
- [x] Use PHP includes to split pages into header, footer,etc.

**Comment by super3** [comment]
Fixed as of f502f653a0df02951a0cdab7de8f750cccbf2ec9
