### ISSUE TITLE
Add Chinese Language Support (~$800 bounty)

### ISSUE THREAD

**Issue by super3** [super3/invictus.io#2]
**Core Spec:**
Chinese + English minimum, but the more languages supported the better.

**Needed:**
Upon completion, the website needs to be immediately translated to Chinese. This translation needs to be kept on a separate [Github branch](http://gun.io/blog/how-to-github-fork-branch-and-pull-request/). This branch should be updated along with the master branch.

**Todo:**
- [ ] Wait for Bounty Content Completion
- [ ] Create Chinese Language Repo Branch
- [ ] Translate Content
- [ ] Add Script to Automatically Update Chinese Language Website on Server.
